### ISSUE TITLE
Asserting for non-null response entity on rest template not acceptable

### ISSUE THREAD

**Issue by lombritz** [elikoyuncu/StudentRegistrationAPI#2]
https://github.com/elikoyuncu/StudentRegistrationAPI/blob/e534566c300e952c927c364f82c2315bf25bbc09/src/test/java/com/sputniktechnology/SchoolRegistrationAPI/SchoolRegistrationApiApplicationTests.java#L88

The response will always yield a passed test cuz response entity will never be null, you must assert some content in the response is actually what you expect.

**Comment by elikoyuncu** [comment]
Hmmm... will fix then.
