### ISSUE TITLE
Unnecessary servlet initializer @SpringBootApplication on the SchoolRegistrationApiApplication.java is enough for spinning this application

### ISSUE THREAD

**Issue by lombritz** [elikoyuncu/StudentRegistrationAPI#3]
https://github.com/elikoyuncu/StudentRegistrationAPI/blob/e534566c300e952c927c364f82c2315bf25bbc09/src/main/java/com/sputniktechnology/SchoolRegistrationAPI/ServletInitializer.java#L6

**Comment by lombritz** [comment]
Servlet initializer is only used when using WAR packaging for the spring boot projects

**Comment by elikoyuncu** [comment]
Hmm... nice to know this. Thank you!
