### ISSUE TITLE
Amazing docs but forgot to say it is required to have MYSQL running or provide the command to run a local container 

### ISSUE THREAD

**Issue by lombritz** [elikoyuncu/StudentRegistrationAPI#4]
https://github.com/elikoyuncu/StudentRegistrationAPI/blob/e534566c300e952c927c364f82c2315bf25bbc09/README.md?plain=1#L77

**Comment by elikoyuncu** [comment]
MySQL and its version are stated in the doc. Please recheck. Thank you!
