### ISSUE TITLE
Tests require MYSQL instance to be running locally, probably best to use testcontainers or an in-memory lightweight DB 

### ISSUE THREAD

**Issue by lombritz** [elikoyuncu/StudentRegistrationAPI#6]
https://github.com/elikoyuncu/StudentRegistrationAPI/blob/e534566c300e952c927c364f82c2315bf25bbc09/src/test/java/com/sputniktechnology/SchoolRegistrationAPI/SchoolRegistrationApiApplicationTests.java#L23

**Comment by elikoyuncu** [comment]
Yes, maybe.
