### ISSUE TITLE
Project is missing script for creating stored procedures.

### ISSUE THREAD

**Issue by lombritz** [elikoyuncu/StudentRegistrationAPI#7]
https://github.com/elikoyuncu/StudentRegistrationAPI/blob/e534566c300e952c927c364f82c2315bf25bbc09/src/main/java/com/sputniktechnology/SchoolRegistrationAPI/base/Result.java#L13

**Comment by elikoyuncu** [comment]
Will provide all DDLs for SPs and let you know.
